INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Cine', 'Barrios', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.value = 'Cine' AND parent_id IS NULL));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Teatro', 'Barrios', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.value = 'Teatro' AND parent_id IS NULL));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Recitales', 'Barrios', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.value = 'Recitales' AND parent_id IS NULL));


INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Abasto', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Almagro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Avellaneda', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Azul', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Banfield', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Barracas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Barrio Norte', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Belgrano', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Berazategui', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Boedo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Caballito', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Capital Federal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Chacras de Coria', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Chateau', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Colegiales', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Congreso', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Córdoba', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Costanera', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Devoto', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Flores', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Florida', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Gualeguaychú', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Hurlingham', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Ituzaingó', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Junín', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Boca', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Paternal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Plata', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Lanús', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Las Toninas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Liniers', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Lomas de Zamora', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Los Cardales', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Los Hornillos', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mar del Plata', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mataderos', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mendoza', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mercedes', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Merlo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Microcentro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Monserrat', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Montevideo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Nuevo Bajo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Núñez', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Olavarría', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Once', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Palermo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Paraje Alfar', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Parque Centenario', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Posadas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Puerto Madero', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Ramos Mejía', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Recoleta', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Retiro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Rosario', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Saavedra', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Antonio de Areco', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Antonio de Padua', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Bernardo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Carlos de Bariloche', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Clemente del Tuyú', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Cristóbal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Isidro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Justo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Martín', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Miguel', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Telmo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Santa Clara del Mar', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Santa Fe', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Temperley', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Unquillo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Vicente López', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Adelina', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa del Parque', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Gesell', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Lugano', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa María', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Pueyrredón', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Otros', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Cine' AND b.value = 'Barrios'));




INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Abasto', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Almagro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Avellaneda', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Azul', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Banfield', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Barracas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Barrio Norte', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Belgrano', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Berazategui', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Boedo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Caballito', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Capital Federal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Chacras de Coria', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Chateau', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Colegiales', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Congreso', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Córdoba', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Costanera', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Devoto', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Flores', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Florida', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Gualeguaychú', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Hurlingham', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Ituzaingó', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Junín', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Boca', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Paternal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Plata', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Lanús', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Las Toninas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Liniers', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Lomas de Zamora', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Los Cardales', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Los Hornillos', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mar del Plata', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mataderos', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mendoza', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mercedes', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Merlo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Microcentro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Monserrat', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Montevideo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Nuevo Bajo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Núñez', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Olavarría', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Once', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Palermo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Paraje Alfar', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Parque Centenario', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Posadas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Puerto Madero', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Ramos Mejía', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Recoleta', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Retiro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Rosario', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Saavedra', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Antonio de Areco', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Antonio de Padua', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Bernardo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Carlos de Bariloche', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Clemente del Tuyú', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Cristóbal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Isidro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Justo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Martín', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Miguel', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Telmo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Santa Clara del Mar', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Santa Fe', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Temperley', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Unquillo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Vicente López', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Adelina', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa del Parque', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Gesell', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Lugano', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa María', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Pueyrredón', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Otros', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Teatro' AND b.value = 'Barrios'));


INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Abasto', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Almagro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Avellaneda', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Azul', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Banfield', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Barracas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Barrio Norte', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Belgrano', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Berazategui', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Boedo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Caballito', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Capital Federal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Chacras de Coria', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Chateau', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Colegiales', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Congreso', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Córdoba', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Costanera', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Devoto', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Flores', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Florida', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Gualeguaychú', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Hurlingham', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Ituzaingó', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Junín', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Boca', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Paternal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','La Plata', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Lanús', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Las Toninas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Liniers', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Lomas de Zamora', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Los Cardales', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Los Hornillos', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mar del Plata', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mataderos', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mendoza', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Mercedes', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Merlo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Microcentro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Monserrat', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Montevideo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Nuevo Bajo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Núñez', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Olavarría', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Once', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Palermo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Paraje Alfar', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Parque Centenario', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Posadas', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Puerto Madero', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Ramos Mejía', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Recoleta', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Retiro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Rosario', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Saavedra', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Antonio de Areco', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Antonio de Padua', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Bernardo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Carlos de Bariloche', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Clemente del Tuyú', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Cristóbal', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Isidro', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Justo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Martín', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Miguel', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','San Telmo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Santa Clara del Mar', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Santa Fe', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Temperley', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Unquillo', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Vicente López', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Adelina', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa del Parque', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Gesell', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Lugano', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa María', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Villa Pueyrredón', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
INSERT INTO `entretenerse`.`attributes` (name, value, parent_id) VALUES ('Barrio','Otros', (SELECT b.id FROM `entretenerse`.`attributes` b WHERE b.name = 'Recitales' AND b.value = 'Barrios'));
